databases:
  - name: example_DB
    databaseName: example_db_8qx8
    user: example_db_8qx8_user

services:
  - type: web
    name: ec_site
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: example_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false