databases:
  - name: example_DB
    databaseName: example_db_dgjo
    user: example_db_dgjo_user

services:
  - type: web
    name: ec_site
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: example_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2